// Generated by BUCKLESCRIPT VERSION 3.1.4, PLEASE EDIT WITH CARE
'use strict';

var $$Array = require("bs-platform/lib/js/array.js");
var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Data$ReactTemplate = require("./Data.bs.js");
var Caml_builtin_exceptions = require("bs-platform/lib/js/caml_builtin_exceptions.js");

var component = ReasonReact.reducerComponent("Page");

function make(_, _$1) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (self) {
              var s = self[/* state */1];
              var u = s[/* users */0];
              return React.createElement("div", undefined, React.createElement("button", {
                              onClick: (function () {
                                  return Curry._1(self[/* send */3], /* Get */0);
                                })
                            }, "cliiick"), React.createElement("div", undefined, u ? $$Array.map((function (user) {
                                      return React.createElement("div", {
                                                  key: user[/* username */0]
                                                }, user[/* username */0]);
                                    }), u[0]) : "No users"));
            }),
          /* initialState */(function () {
              return /* record */[/* users : None */0];
            }),
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */(function (action, state) {
              if (typeof action === "number") {
                if (action !== 0) {
                  throw [
                        Caml_builtin_exceptions.match_failure,
                        [
                          "Component1.re",
                          9,
                          4
                        ]
                      ];
                } else {
                  return /* UpdateWithSideEffects */Block.__(2, [
                            state,
                            (function (self) {
                                Data$ReactTemplate.get(/* () */0).then((function (users) {
                                        return Promise.resolve(Curry._1(self[/* send */3], /* SetUsers */[users]));
                                      }));
                                return /* () */0;
                              })
                          ]);
                }
              } else {
                return /* Update */Block.__(0, [/* record */[/* users : Some */[action[0]]]]);
              }
            }),
          /* subscriptions */component[/* subscriptions */13],
          /* jsElementWrapped */component[/* jsElementWrapped */14]
        ];
}

exports.component = component;
exports.make = make;
/* component Not a pure module */
