// Generated by BUCKLESCRIPT VERSION 3.1.4, PLEASE EDIT WITH CARE
'use strict';


var server = "https://immense-river-25513.herokuapp.com/locations";

function get() {
  return fetch(server).then((function (prim) {
                  return prim.text();
                })).then((function (text) {
                return Promise.resolve((console.log(text), /* () */0));
              }));
}

exports.server = server;
exports.get = get;
/* No side effect */
